### ISSUE TITLE
Documentation leads to 403 error

### ISSUE THREAD

**Issue by NoName298GH** [ctruLua/ctruLua#13]
I was trying to go to the documentation on the website, but it gave me a 403 error.
Is there anyway to fix or get around this?

![SCR-20241024-tgqf](https://github.com/user-attachments/assets/508c0655-5f01-4f49-9e95-4baebf998f95)

**Comment by Reuh** [comment]
I migrated the documentation to another server a few months agos, looks like there was a configuration issue.

This should be fixed now !

**Comment by NoName298GH** [comment]
Nice! Thank you!
