### ISSUE TITLE
HTTPS support in httpc is broken

### ISSUE THREAD

**Issue by dogtopus** [ctruLua/ctruLua#8]
Although http:C has HTTPS support, due to the missing of certificate chain manipulating functions (AddTrustedRootCA, etc.) it is almost unusable since http:C doesn't trust any CA by default.

**Comment by Firew0lf** [comment]
The ctrulib doesn't have the SSL support in httpc yet. I'll add it to ctrµLua as soon as possible. Or even to the ctrulib maybe.

**Comment by Firew0lf** [comment]
https://github.com/smealum/ctrulib/commit/d769879933b5e672e817e6082e6edb20f5924a96

I'll add it to ctrµLua today :smiley: .

**Comment by dogtopus** [comment]
After I added the correct CA certificate using `AddTrustedRootCA`, httpc still said the certificate is not trusted...
Seems that `AddTrustedRootCA` is not sufficient to make 3DS trust a CA...

**Comment by Firew0lf** [comment]
I'll take a look at this. A lot of HTTP:c functions are not implemented by the ctrulib, including a lot of functions related to https. And according to [this page](https://3dbrew.org/wiki/HTTPC:AddTrustedRootCA) and [this one](https://3dbrew.org/wiki/SSLC:AddTrustedRootCA), the DER certificate is not parsed, only added to the chain.

**Comment by dogtopus** [comment]
A lot of ssl related httpc commands were implemented in ctrulib recently and there is https://github.com/yellows8/ctr-httpwn which uses these commands

**Comment by Reuh** [comment]
@Firew0lf is pretty busy with IRL stuff for now. I know he started implementing the new functions in ctrµLua, but I don't know what he has done so far.

**Comment by Firew0lf** [comment]
I added SSL support to the sockets, it's not as easy to use as httpContexts, but it should work. The HTTP protocol is not the hardest thing to implement in Lua.

**Comment by Firew0lf** [comment]
I added the function `:addDefaultCert()` to the HTTPContexts, now they should be able to connect to any https server using a root certificate built-in the 3DS.
